[wokwi]
version = 1
firmware = '.pio/build/esp32/firmware.bin'
elf = '.pio/build/esp32/firmware.elf'
# Optional: connect with "Serial Monitor" extension → TCP → localhost:4000 @ 115200
rfc2217ServerPort = 4000
